plugins{
    id 'java'
    id 'org.springframework.boot' version '3.4.5'
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'chanhnguyen.hoppy.thehobbitstore'
version = rootProject.version

repositories {
    mavenCentral()
    maven {
        name = 'Sonatype Snapshots'
        url = 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

compileJava {
    options.annotationProcessorPath = configurations.annotationProcessor
}

dependencies {
    implementation project(':c-core')
    implementation project(':b-api')

    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

    implementation 'org.apache.commons:commons-lang3:3.14.0'
    implementation 'org.apache.commons:commons-collections4:4.4'
    implementation 'org.springframework.boot:spring-boot-starter-web:3.4.5'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc:3.4.5'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    implementation 'org.flywaydb:flyway-core:10.13.0'
    implementation 'org.flywaydb:flyway-database-postgresql:10.13.0'
    implementation 'org.postgresql:postgresql:42.7.3'
    implementation 'jakarta.validation:jakarta.validation-api:3.0.2'
    implementation 'de.huxhorn.sulky:de.huxhorn.sulky.ulid:8.3.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.6.0'
    testImplementation 'org.testng:testng:7.10.2'
    testImplementation 'org.mockito:mockito-core:5.2.0'
    testImplementation 'org.springframework.boot:spring-boot-starter-test:3.4.5'
    testImplementation 'com.intuit.karate:karate-junit5:1.4.1'
    testImplementation 'org.testcontainers:junit-jupiter:1.19.7'
    testImplementation 'org.testcontainers:postgresql:1.19.7'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers:3.4.5'
}

sourceSets {
    test {
        resources {
            srcDir file('src/test/java')
            exclude '**/*.java'
        }
    }
}

test {
    useJUnitPlatform()
    systemProperty "karate.options", System.properties.getProperty("karate.options")
    systemProperty "karate.env", System.properties.getProperty("karate.env")
    outputs.upToDateWhen { false }
}
